# Project information
site_name: AutoAgora Agents
site_url: https://semiotic-ai.github.io/autoagora-agents/

# Repository
repo_name: semiotic-ai/autoagora-agents
repo_url: https://github.com/semiotic-ai/autoagora-agents
edit_uri: ""

# Configuration
theme:
  name: material
  features:
  - content.code.annotate
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          docstring_section_style: list
          members_order: source
          show_root_heading: true
          show_signature_annotations: false
          heading_level: 3
          filters: ["!_"]
- mike

# Customization
extra:
  version:
    provider: mike
    default: latest

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Developer's Guide: index.md
  - Reference:
    - Agents:
      - Algorithm: code/algorithm.md
      - Buffer: code/buffer.md
      - Controller: code/controller.md
      - Distribution: code/distribution.md
    - Simulation:
      - Distributor: code/distributor.md
      - Dynamics: code/dynamics.md
      - Environment: code/environment.md
      - Observation: code/observation.md
      - Reward: code/reward.md

  - Development:
    - Contributing: contributing.md