name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  conventional-commits-check:
    name: Check conventional commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install commitizen
        run: pip install commitizen
      - name: commitizen check
        run: cz check --rev-range ${{ github.event.pull_request.base.sha }}..HEAD
  dco-check:
    uses: cncf/dcochecker/.github/workflows/dco.yml@main
